- name: Common setup for bastion hosts
  hosts: bastion
  become: true
  gather_facts: true
  roles:
    - common
    - security

- name: Common setup for monitoring nodes
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - common
    - security

- name: Ensure Node Exporter on monitoring nodes
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - node_exporter

- name: Configure Prometheus on monitoring nodes
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - prometheus

- name: Configure Alertmanager on monitoring nodes
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - alertmanager

- name: Configure EFS mounts for Grafana
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - efs

- name: Configure Grafana servers
  hosts: monitoring
  become: true
  gather_facts: true
  roles:
    - grafana