---
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted

- name: Restart mock log generator
  ansible.builtin.systemd:
    name: mock_log_generator
    state: restarted
